import = ["/Users/jmb/.config/alacritty/theme/themes/tokyo-night-storm.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 750
thickness = 0.5

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 14.0

[font.bold]
family = "Monofur Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Monofur Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Monofur Nerd Font"
style = "Italic"

[font.normal]
family = "Monofur Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/opt/homebrew/bin/tmux"

[window]
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
